# DO NOT use version anymore — it's deprecated in Docker Compose v2+
services:
  db:
    image: postgres:16
    restart: always
    ports:
      - "5433:5432"
    env_file: .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: crb12345
      POSTGRES_DB: sigam
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./server
    image: sigam-backend:latest
    ports:
      - "3001:3001"
    env_file: .env
    depends_on:
      - db
    command: >
      sh -c "npx ts-node prisma/run-all-seeds.ts && npm run start:prod"

  frontend:
    build: ./client
    image: sigam-frontend:latest
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
      INTERNAL_API_URL: http://backend:3001
    depends_on:
      - backend

volumes:
  pgdata:
